name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    # Run the workflow on a Linux environment
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89

    steps:
      # Checkout the source code
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup Node.js v16
      - name: Setup NPM
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Cache node dependencies for faster install for the next workflow
      - name: Cache Node Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      # Install the dependencies
      - name: Install API NPM Dependencies
        working-directory: ./client
        run: npm ci

      # Run the Cypress tests
      - name: Run API Tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: client
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: "UI - Chrome"
          spec: cypress/integration/app/*
