name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NPM
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache Node Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install API NPM Dependencies
        working-directory: ./api
        run: npm ci

      - name: Install Client NPM Dependencies
        working-directory: ./client
        run: npm ci


      - name: Run API Tests
        working-directory: ./api
        run: npm test

      - name: Run Client Tests
        working-directory: ./client
        run: npm test
